### PR TITLE
feat(localization): update pseudo translation

### PR DESCRIPTION
**Pull request by jona7150**
Updated translation using Jenkins. Please review and merge @dfeinzimer 

 CC: @michi6571 @masa6674

### CODE REVIEW

**Comment by jona7150** [comment]
Added another commit for pseudo translation updates: eda17a3

**Review by dfeinzimer — COMMENTED** [review]
Thanks for doing this and picking up the new changes.

Going forward how do we kick off the translation process again when we have new strings? Do we just update `l10n-staging` and you guys monitor it for changes?

Any reason for the deletion of the following files?
Sources/ArcGISToolkit/Resources/no.lproj/Localizable.strings
Sources/ArcGISToolkit/Resources/zh-CN.lproj/Localizable.strings
Sources/ArcGISToolkit/Resources/zh-HK.lproj/Localizable.strings
Sources/ArcGISToolkit/Resources/zh-TW.lproj/Localizable.strings

**Comment by michi6571** [comment]
> Thanks for doing this and picking up the new changes.
> 
> Any reason for the deletion of the following files? Sources/ArcGISToolkit/Resources/no.lproj/Localizable.strings Sources/ArcGISToolkit/Resources/zh-CN.lproj/Localizable.strings Sources/ArcGISToolkit/Resources/zh-HK.lproj/Localizable.strings Sources/ArcGISToolkit/Resources/zh-TW.lproj/Localizable.strings

@dfeinzimer, thank you for confirming our fix of the missing files: https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/426#issuecomment-1786122112.

It looks like we mistakenly removed these target files while we are adding the missing target files.  We will bring these files back and create a new commit to this PR shortly. 
- no.lproj
- zh-CN.lproj
- zh-TW.lproj
- zh-HK.lproj

> Going forward how do we kick off the translation process again when we have new strings? Do we just update l10n-staging and you guys monitor it for changes?

Based on your request in the build setup form, we run the pseudo/translation build on-demand only.  If you would like us to set the automated Pseudo build schedule between 6 PM Pacific to 6 AM Pacific (e.g., 12 AM daily, 10 PM daily), please let us know.  Please check with Ryan Olson if he wants us to set the build schedule for https://devtopia.esri.com/runtime/swift/.  We can set the build schedule for both arcgis-maps-sdk-swift-toolkit and swift rpos.  

cc @masa6674

**Comment by dfeinzimer** [comment]
> If you would like us to set the automated Pseudo build schedule between 6 PM Pacific to 6 AM Pacific (e.g., 12 AM daily, 10 PM daily), please let us know.

That sounds like it would be a good thing to have - I will check with him.

Is it something that'll be fairly straightforward and quick for your team to setup?

**Review by dfeinzimer — APPROVED** [review]
Appears that all pseudo files are updated correctly now.

**Comment by michi6571** [comment]
Thank you, @dfeinzimer.  The setting up the scheduled build should be quick.  

cc @masa6674

**Comment by dfeinzimer** [comment]
@michi6571 I presented the idea to the Swift team. All positive responses. Please go ahead and schedule the regular builds/checks for both repos. Thanks!

**Comment by michi6571** [comment]
Thank you for the update, @dfeinzimer.  We will set the automated pseudo build schedule around 12 AM daily.

cc @masa6674

**Comment by michi6571** [comment]
@dfeinzimer Both pseudo builds for arcgis-maps-sdk-swift-toolkit and swift have been schedule to run daily at 12 AM starting tonight. 

cc @masa6674

**Comment by dfeinzimer** [comment]
> Both pseudo builds for arcgis-maps-sdk-swift-toolkit and swift have been schedule to run daily at 12 AM starting tonight.

Fantastic, thank you!

cc @rolson, @mhdostal

**Pull request merged**
