### PR TITLE
`FeatureFormView` - Make form input views public, support custom layouts

### PR DESCRIPTION
**Pull request by dfeinzimer**
Ref Apollo 294 & 353

### CODE REVIEW

**Comment by mhdostal** [comment]
@dfeinzimer This looks great. Does the keyboard avoidance/scrolling work OK with custom views? Also, you should keep the original initializer along with the overloaded one you added.

**Comment by dfeinzimer** [comment]
> Does the keyboard avoidance/scrolling work OK with custom views?

Keyboard avoidance should work automatically, yes. Scrolling a focused field to the top of the form/screen would fall on the user as they would supply the ScrollView and the associated proxy/reader to achieve that.

> Also, you should keep the original initializer along with the overloaded one you added.

👍 I will keep both.

**Comment by dfeinzimer** [comment]
@mhdostal Should we prepend `Form` onto the names of the new public views to communicate their intended usage? E.g. `ComboBoxInput` -> `FormComboBoxInput`

**Comment by mhdostal** [comment]
> Should we prepend `Form` onto the names of the new public views to communicate their intended usage? E.g. `ComboBoxInput` -> `FormComboBoxInput`

I can see the reasoning to do that; it makes it explicit that it's part of the Feature Form. However, the associated SDK object is `ComboBoxFormInput`. I think that would be confusing having two objects with very similar names, except for the placement of the word "Form". I can't think of an alternative.

**Comment by dfeinzimer** [comment]
Closing this as not currently planned/prioritized and the branch has fallen significantly behind. The changes will still be available in the [Files changed](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/545/files) tab.

**Pull request closed without merging**
