### PR TITLE
feat(localization): update pseudo translation

### PR DESCRIPTION
**Pull request by jona7150**
Updated translation using Jenkins. Please review and merge @dfeinzimer 

 CC: @michi6571 @masa6674

### CODE REVIEW

**Review by dfeinzimer — APPROVED** [review]

**Comment by dfeinzimer** [comment]
@jona7150 @michi6571 @masa6674 we noticed that some languages weren't included in this update. Are the following no longer supported?

nb
zh-Hans-CN
zh-Hans
zh-Hant-HK
zh-Hant-TW

**Comment by michi6571** [comment]
@dfeinzimer Thank you for pointing it out.  We will review. 

cc @jona7150 @masa6674

**Comment by michi6571** [comment]
@dfeinzimer We would like to run another build to add the missing languages.  It seems that the l10n-staging branch is not available anymore.  Could you please create the branch so that we can generate a new PR for the missing target files?  Thank you. 

cc @jona7150 @masa6674

**Comment by dfeinzimer** [comment]
@michi6571 Yes that sounds good, thank you! I've recreated the staging branch.

**Comment by michi6571** [comment]
Thank you, @dfeinzimer. 

cc @jona7150 @masa6674

**Pull request merged**
