### PR TITLE
feat(localization): update translation

### PR DESCRIPTION
**Pull request by jona7150**
Updated translation using Jenkins. Please review and merge @dfeinzimer 

 CC: @michi6571 @masa6674

### CODE REVIEW

**Review by dfeinzimer — COMMENTED** [review]
Hi @jona7150, I see the following files are all deletions. Is this expected?

`Sources/ArcGISToolkit/Resources/no.lproj/Localizable.strings`
`Sources/ArcGISToolkit/Resources/zh-CN.lproj/Localizable.strings`
`Sources/ArcGISToolkit/Resources/zh-HK.lproj/Localizable.strings`
`Sources/ArcGISToolkit/Resources/zh-TW.lproj/Localizable.strings`

**Comment by rolson** [comment]
@michi6571

**Comment by rolson** [comment]
cc David Feinzimer

**Comment by rolson** [comment]
@MasaGithub88

**Comment by rolson** [comment]
@michi6571 did you get this?

**Comment by jona7150** [comment]
Added another commit for translation updates: 1995718

**Comment by michi6571** [comment]
> Hi @jona7150, I see the following files are all deletions. Is this expected?
> 
> `Sources/ArcGISToolkit/Resources/no.lproj/Localizable.strings` `Sources/ArcGISToolkit/Resources/zh-CN.lproj/Localizable.strings` `Sources/ArcGISToolkit/Resources/zh-HK.lproj/Localizable.strings` `Sources/ArcGISToolkit/Resources/zh-TW.lproj/Localizable.strings`

@rolson Thank you for pointing it out.  We have fixed in the Generate/Translation build.  Here is the commit of the fix: 
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/commit/19957186fea64b519012eb81f5c75a1aae069b8f

cc @jona7150 @MasaGithub88

**Pull request merged**
