### PR TITLE
BasemapGallery test fix

### PR DESCRIPTION
**Pull request by mhdostal**
Fixes the "init" test in response to changes in #328

### CODE REVIEW

**Review by dfeinzimer — COMMENTED** [review]
The test passes but then a few moments later I get a crash in core, still looking

Screenshot 2023-08-14 at 10 15 11

**Comment by mhdostal** [comment]
> The test passes but then a few moments later I get a crash in core in response handling, still looking.

Weird. I was running all the tests and I didn't get a crash. If I run just the BasemapGallery tests or simply the `Init` test, it crashes.

**Review by dfeinzimer — APPROVED** [review]
For what its worth, seems to crash on `main`/`200.1` so I don't think this is a regression. Should we give this its own issue?

**Comment by mhdostal** [comment]
> Should we give this its own issue?

Yes, it's own issue. If it's not a regression, then we'll fix it next release.

**Pull request merged**
