### PR TITLE
Better integrate DocC

### PR DESCRIPTION
**Pull request by dfeinzimer**
Related Swift #3793

This PR aims to makes use of DocC to enhance the toolkit documentation. Currently, only changes have been made for the Compass but this PR can be expanded to all of the components if we choose to move forward.

DocC can be hosted (on GitHub pages in this repo or elsewhere) and replace our [existing documentation](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/tree/main/Documentation) with formatted DocC that is familiar to Swift developers.

Our typical documentation for a component follows this format:

- A descriptive paragraph about the component and its capabilities. This description can be moved in the component's main Swift file as a DocC comment, making it easier to keep current:
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/5005a7f3c88d00716a7874c2762e84993e8f7035/Sources/ArcGISToolkit/Components/Compass/Compass.swift#L24-L27

- A screenshot of the component in use. DocC will render images, so this too can be inlined in the component's main Swift file:
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/5005a7f3c88d00716a7874c2762e84993e8f7035/Sources/ArcGISToolkit/Components/Compass/Compass.swift#L19

- A list of the component's initializers. DocC will handle this for us so no need to keep separate doc updated whenever there's API changes.

- A list of the component's modifiers. Same here, DocC can take care of this automatically.

- A small code snippet with basic usage. DocC has [Interactive Tutorials](https://developer.apple.com/documentation/docc/building-an-interactive-tutorial) which can help highlight step by step how to integrate a component. I can see this being especially useful for the more complicated components like search.

With all of that said what does this get us? 

 - Nicely formatted documentation that stylistically matches the Swift SDK, Apple's doc, and is familiar to Swift developers: 
    Screenshot 2023-04-19 at 18 34 58

  - Interactive tutorials that guide usage step-by-step:
  
    [tutorial](https://user-images.githubusercontent.com/16397058/233235921-f0c4486f-00a6-4e8c-bba5-c8ba6de73ae3.mov)

For demonstration purposes of this PR I set up a test repo with GitHub pages to show how this would appear when hosted. This can be seen [here](https://dfeinzimer.github.io/docCTest/documentation/arcgistoolkit/).

The doc build would need to be ran manually and/or eventually automated using a script similar to:
```bash
xcodebuild docbuild -scheme arcgis-maps-sdk-swift-toolkit \
    -destination generic/platform=iOS \
    OTHER_DOCC_FLAGS="--transform-for-static-hosting --hosting-base-path arcgis-maps-sdk-swift-toolkit --output-path /docs"
```

See also: 
 - [Build interactive tutorials using DocC (WWDC 21)](https://developer.apple.com/videos/play/wwdc2021/10235/)
 - [Host and automate your DocC documentation (WWDC 21)](https://developer.apple.com/videos/play/wwdc2021/10236/)
 - [Publishing to GitHub Pages](https://apple.github.io/swift-docc-plugin/documentation/swiftdoccplugin/publishing-to-github-pages/)

### CODE REVIEW

**Comment by mhdostal** [comment]
This is really nice! A few questions:
- Would we update the main repo README to point to the DocC versions for each component?
- Would we put the generated DocC code in GitHub? Or would it just be built locally? (If so, what about the README?)
- When does it make sense for the build script to run? Would we run it locally as part of the PR process? Or would it be run as part of a PR verification step on GitHub?

I like the idea of putting all the doc in the Swift files as it will eliminate duplication of text. The tutorial looks awesome as well.

Very nice!

**Comment by dfeinzimer** [comment]
> Would we update the main repo README to point to the DocC versions for each component?

Yep, that would be the idea. For example, in these links:
Screenshot 2023-04-20 at 14 45 54

Compass could instead link to [this page](https://dfeinzimer.github.io/docCTest/documentation/arcgistoolkit/compass).

> Would we put the generated DocC code in GitHub? Or would it just be built locally? (If so, what about the README?)

Depends on how we'd like to host it (if we host it at all - which we should, so it can be more accessible and linked to).

  - If we host if via [GitHub Pages](https://pages.github.com/) (like my demo linked above is) then yes. We just configure GitHub Pages to host from the directory in the repo we push the generated doc into and it would have a url like https://esri.github.io/arcgis-maps-sdk-swift-toolkit/documentation/arcgistoolkit
  - If we host it on the developer site like the Swift SDK at https://developers.arcgis.com/swift/api-reference/documentation/arcgis/ then we wouldn't need to do this.

> When does it make sense for the build script to run? Would we run it locally as part of the PR process? Or would it be run as part of a PR verification step on GitHub?

I think once per release would be fine. I think we can setup GitHub Actions to build the doc whenever there is a push into main (e.g. when we merge in `v.next`). During development/reviews we can still build and view it locally to make sure everything looks okay via `Product` > `Build Documentation`

Screenshot 2023-04-20 at 15 06 15

**Comment by mhdostal** [comment]
@dfeinzimer Do you have a preference for hosting between GitHub Pages or the ArcGIS Developers site?



> > When does it make sense for the build script to run? Would we run it locally as part of the PR process? Or would it be run as part of a PR verification step on GitHub?
> 
> I think once per release would be fine. I think we can setup GitHub Actions to build the doc whenever there is a push into main (e.g. when we merge in `v.next`). During development/reviews we can still build and view it locally to make sure everything looks okay via `Product` > `Build Documentation`

I'm thinking of when we create a new component and merge that into `v.next`. It would be nice if the `v.next` branch would have the complete documentation, so people looking for the latest and greatest could see what's there. An issue for a new component (or for when the API for an existing component is modified) wouldn't be complete unless the documentation was finished.

**Comment by dfeinzimer** [comment]
> I'm thinking of when we create a new component and merge that into `v.next`. It would be nice if the `v.next` branch would have the complete documentation, so people looking for the latest and greatest could see what's there. An issue for a new component (or for when the API for an existing component is modified) wouldn't be complete unless the documentation was finished.

Agreed. With GitHub Pages there seems to be a limitation of hosting [1 branch per repo](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#:~:text=You%20can%20specify%20which%20branch%20and%20folder%20to%20use%20as%20your%20publishing%20source.) (so either `main` or `v.next`) and we might need to pay compute time time for GitHub Actions to run the doc builds. 

If we can make it happen, I think hosting the toolkit docs alongside the Swift docs on developers.arcgis.com would be optimal. For Swift, I know there's also a hosted version of daily doc builds so I think it'd be possible for us to get `main` and `v.next` both hosted.

**Review by mhdostal — DISMISSED** [review]
Are there any links that need updating, now that the backend DocC work is done?

**Comment by dfeinzimer** [comment]
DocC hosting setup complete. This is ready to merge now. Resolved one merge conflict, ready for re-review.

**Review by mhdostal — APPROVED** [review]

**Pull request merged**
