### PR TITLE
Add UI Test Runner target to the Examples app

### PR DESCRIPTION
**Pull request by dfeinzimer**
Related https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/issues/362, Apollo 47

This PR serves as an alternative to #364.

#364 creates an entire new testing app with a UI testing target. While writing the starter tests within, I noticed that the test views weren't requiring any differences from the example views we've already written in the Examples app. For that reason, I've opened this PR which simply adds a UI testing target to the existing examples app.

### CODE REVIEW

**Comment by mhdostal** [comment]
This is certainly cleaner and more convenient than the original PR. However, I'm wondering if we're not trying to solve two separate issues now with the Examples. They are mainly to showcase the component and demonstrate how to use it. Two somewhat related things:

- Are the examples, as they're defined, enough to fully test the component? Meaning, is there component functionality that we'd want to test which is not exposed by the example?

- Given that the examples are for showcasing/demonstrating the component, I don't want to start "cluttering" them in order to get more test coverage.

Thoughts?

**Comment by rolson** [comment]
> Are the examples, as they're defined, enough to fully test the component?

No.

> Given that the examples are for showcasing/demonstrating the component, I don't want to start "cluttering" them in order to get more test coverage.

I strongly agree.

The two goals should not be conflated. Tests are tests, examples are to show the minimum code required to use a component. I don't see these goals as compatible.

**Comment by dfeinzimer** [comment]
It's a good point and yes I can see this as an issue. When we go to write tests for the Form component we may want to use a number of different forms with differing fields and configurations.

**Comment by mhdostal** [comment]
@rolson Thanks for the comments, I think we should keep the two separate, examples and tests. Yes, for the simpler components the test view and example view may be very similar, but for more complex components they will diverge quite a bit.

**Comment by dfeinzimer** [comment]
Closing in favor of #364

**Pull request closed without merging**
