### PR TITLE
Drop AR components from Catalyst

### LINKED ISSUE #889: AR Components should be marked as unavailable for Mac Catalyst
They don't make much sense in the context of mac catalyst so they shouldn't be available there.

### PR DESCRIPTION
**Pull request by dfeinzimer**
Closes #889 

cc @dg0yal

### CODE REVIEW

**Review by zkline101 — APPROVED** [review]

**Comment by dfeinzimer** [comment]
Does this break semantic versioning? Do we need to do a deprecation instead?

**Comment by zkline101** [comment]
> Does this break semantic versioning? 

Technically yes because this is a breaking change but these components I'm pretty sure never worked for mac catalyst anyway, right? Did you running the examples?

**Comment by dfeinzimer** [comment]
> Did you running the examples?

Flyover somewhat works with a mouse but it's not a great experience. Tabletop and World Scale are non-operational.

**Comment by rolson** [comment]
I think it is ok to deprecate all three on Mac Catalyst. Technically a breaking change, but it shouldn't affect anybody.

**Review by rolson — APPROVED** [review]

**Review by mhdostal — APPROVED** [review]

**Pull request merged**
